### ISSUE TITLE
type is sometimes undefined

### ISSUE THREAD

**Issue by kenahrens** [bretcope/node-gc-profiler#10]
This is a great library, I've recently been testing it out to log the GC events. One thing that I noticed is that sometimes type will come back as undefined. Usually it's Scavenge or MarkSweepCompact, but every once in a while I get a result like this:

```
{ duration: 0.317,
  type: undefined,
  forced: false,
  flags: 0,
  pid: 11419,
  timestamp: 1471027931000 }
```

I just touched the info object to add pid and change the date to a timestamp. Here is my code snippet that does that:

```
profiler.on('gc', function (info) {
  info.pid = process.pid;
  info.timestamp = info.date.getTime();
  delete info.date;
  console.log(info);
});
```

Any idea why the type is sometimes undefined?

**Comment by bretcope** [comment]
It looks like v8 has added [more GC types](https://github.com/v8/v8/blob/ca9ec36eb5881f73c1ac1b5a5df710227ad96fae/include/v8.h#L5228). I don't have time today, but those new types should get added, and there should probably be an additional field `typeFlags` which exposes the numerical value to make it a little more future compatible.

Since I don't use node much these days, this library could really use a proper maintainer.

**Comment by bartoszwalacik** [comment]
@bretcope it looks like a small maintenance task ...
